Repository YAPP-Github/26th-App-Team-3-BE, pull requests merged in 2025-07, with the labels that each got.

#22 [T3-87] 루틴 업데이트 엣지 케이스 추가
  src/main/java/bitnagil/bitnagil_backend/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/bitnagil/bitnagil_backend/auth/jwt/JwtUtil.java
  src/main/java/bitnagil/bitnagil_backend/auth/kakao/service/CustomOAuth2UserService.java
  src/main/java/bitnagil/bitnagil_backend/global/config/SecurityConfig.java
  src/main/java/bitnagil/bitnagil_backend/routine/domain/Routine.java
  src/main/java/bitnagil/bitnagil_backend/routine/domain/SubRoutine.java
  src/main/java/bitnagil/bitnagil_backend/routine/request/SubRoutineInfo.java
  src/main/java/bitnagil/bitnagil_backend/routine/request/UpdateRoutineRequest.java
  src/main/java/bitnagil/bitnagil_backend/routine/service/RoutineService.java
  src/main/java/bitnagil/bitnagil_backend/user/repository/UserRepository.java
  src/main/java/bitnagil/bitnagil_backend/user/service/UserAuthService.java
  src/test/java/bitnagil/bitnagil_backend/routine/service/RoutineServiceTest.java
  src/test/java/bitnagil/bitnagil_backend/user/service/UserAuthServiceTest.java
Labels: fix

#34 v1.0.0: release 1차 운영 배포
  .github/release-drafter-config.yml
Labels: feature, major

#40 [T3-125] 유저 닉네임 조회, 감정 구슬 조회 API
  src/main/java/bitnagil/bitnagil_backend/emotionMarble/controller/EmotionMarbleController.java
  src/main/java/bitnagil/bitnagil_backend/emotionMarble/controller/spec/EmotionMarbleSpec.java
  src/main/java/bitnagil/bitnagil_backend/emotionMarble/response/EmotionMarbleTypeResponse.java
  src/main/java/bitnagil/bitnagil_backend/emotionMarble/service/EmotionMarbleMapper.java
  src/main/java/bitnagil/bitnagil_backend/emotionMarble/service/EmotionMarbleService.java
  src/main/java/bitnagil/bitnagil_backend/onboarding/service/OnboardingService.java
  src/main/java/bitnagil/bitnagil_backend/recommendedRoutine/service/RecommendedRoutineManager.java
  src/main/java/bitnagil/bitnagil_backend/recommendedRoutine/service/RecommendedRoutineMapper.java
  src/main/java/bitnagil/bitnagil_backend/recommendedRoutine/service/RecommendedRoutineService.java
  src/main/java/bitnagil/bitnagil_backend/user/controller/UserController.java
  src/main/java/bitnagil/bitnagil_backend/user/controller/spec/UserSpec.java
  src/main/java/bitnagil/bitnagil_backend/user/response/UserInfoResponse.java
  src/main/java/bitnagil/bitnagil_backend/user/service/UserAuthService.java
  src/main/java/bitnagil/bitnagil_backend/user/service/UserManager.java
  src/main/java/bitnagil/bitnagil_backend/user/service/UserMapper.java
  src/main/java/bitnagil/bitnagil_backend/user/service/UserService.java
Labels: feature

#42 [T3-131] 엔드 포인트 수정 및 루틴 단건 조회 서비스 로직 수정
  src/main/java/bitnagil/bitnagil_backend/emotionMarble/controller/EmotionMarbleController.java
  src/main/java/bitnagil/bitnagil_backend/emotionMarble/controller/spec/EmotionMarbleSpec.java
  src/main/java/bitnagil/bitnagil_backend/emotionMarble/service/EmotionMarbleService.java
  src/main/java/bitnagil/bitnagil_backend/routine/service/RoutineService.java
  src/main/java/bitnagil/bitnagil_backend/user/controller/UserController.java
Labels: fix
